spring.application.name=order-service
spring.mongodb.uri=mongodb+srv://fairuzbinte9_db_user:CLiXNW79ZgB4fGG7@fooddeliverycluster.vcthmp8.mongodb.net/?appName=FoodDeliveryCluster
spring.mongodb.database=order_db